# Development and Test environment configurations are listed here
# for convenience but generally shouldn't be used.
# 
# Replace YOUR_APP with the heroku app name and YOUR_TOKEN with the
# same token used in private_pub.yml of your rails project.

production:
  server: "https://priv-pub.herokuapp.com/faye"
  secret_token: "ed9372dce63339c1dfab840bc32939d1f3ba439061b525a358004e913f60b7d8"
  signature_expiration: 86400 # one day
